dataPath <- "C:/Users/yomaa/OneDrive/University of Chicago/Assignment/Statistical Analytics/RCode/Week4/Group"
data<-read.csv(file=paste(dataPath,"Method_Moments_Data.csv",sep="/"))
library(fitdistrplus)
mmA<-fitdistr(data$A,"exponential")
mmB<-fitdist(data$B,"unif")
DtestA <- ks.test(data$A,"pexp",mmA$estimate[1],mmA$estimate[2])
DtestA
DtestB <- ks.test(data$B,"punif",mmB$estimate[1],mmB$estimate[2])
DtestB
meanX <- round(mean(data$X),2)
meanY <- round(mean(data$Y),2)
sdX <- round(sd(data$X),2)
sdY <- round(sd(data$Y),2)
covXY <- round(cov(data$X,data$Y),2)
corr <- covXY/(sdX*sdY)
slope <- corr*(sdY)/sdX
intercept <- meanY - (slope*meanX)
rsd <- sqrt(sum((data$Y - (intercept+slope*data$X))^2)/(length(data$Y)-2))

print("Sample A is a Normal sample")
print(paste("First parameter for Sample A =",round(mmA$estimate[1],3)))
print(paste("Second parameter for Sample A =",round(mmA$estimate[2],3)))
print(paste("Kolmogorov-Smirnov test Value for Sample A =",round(DtestA$statistic,3)))
print("Sample A is a Uniform sample")
print(paste("First parameter for Sample B =",round(mmB$estimate[1],3)))
print(paste("Second parameter for Sample B =",round(mmB$estimate[2],3)))
print(paste("Kolmogorov-Smirnov test Value for Sample B =",round(DtestB$statistic,3)))
print(paste("Intercept =",round(intercept,3)))
print(paste("Slope =",round(slope,3)))
print(paste("Residual Standard Deviation =",round(rsd,3)))
