dataPath <- ""
LinearModel.Training <- read.table(file = paste(dataPath, 'Week6_Test_Sample_Train.csv', sep = "/"), header = TRUE, sep = " ")
LinearModel.Training <- LinearModel.Training[c(2,1,3)]
nSample.Training <- length(LinearModel.Training[, 1])
head(LinearModel.Training)
plot(LinearModel.Training[, 1], LinearModel.Training[, 2], type = "p", pch = 19)
# Define training samples generated by model 1 and model 2
LinearModel.Training.1 <- cbind(LinearModel.Training[, 1], rep(NA, nSample.Training))
LinearModel.Training.2 <- cbind(LinearModel.Training[, 1], rep(NA, nSample.Training))
LinearModel.Training.1[LinearModel.Training[, 3] * (1:nSample.Training), 2] <- LinearModel.Training[LinearModel.Training[, 3] * (1:nSample.Training), 2]
LinearModel.Training.2[(1 - LinearModel.Training[, 3]) * (1:nSample.Training), 2] <- LinearModel.Training[(1 - LinearModel.Training[, 3]) * (1:nSample.Training), 2]

head(cbind(LinearModel.Training, Trainig1 = LinearModel.Training.1[, 2], Training2 = LinearModel.Training.2[, 2]))
matplot(LinearModel.Training[, 1], cbind(LinearModel.Training.1[, 2], LinearModel.Training.2[, 2]), pch = 16, col = c("green", "blue"), ylab = "Subsamples of the training sample")
EstimatedLinearModel.Training <- lm(Output ~ Input, LinearModel.Training)

EstimatedResiduals.Training <- EstimatedLinearModel.Training$residuals
plot(LinearModel.Training[, 1], EstimatedResiduals.Training)
EstimatedResiduals.Training.1 <- EstimatedResiduals.Training
EstimatedResiduals.Training.2 <- EstimatedResiduals.Training
EstimatedResiduals.Training.1[(LinearModel.Training[, 3] == 0) * (1:nSample.Training)] <- NA
EstimatedResiduals.Training.2[(LinearModel.Training[, 3] == 1) * (1:nSample.Training)] <- NA
# Print the first ten columns to check the separation
head(cbind(AllResiduals = EstimatedResiduals.Training,
           Training1Residuals = EstimatedResiduals.Training.1,
           Training2Residuals = EstimatedResiduals.Training.2,
           TrainingClass = LinearModel.Training[, 3]))
matplot(LinearModel.Training[, 1], cbind(EstimatedResiduals.Training.1,
                                         EstimatedResiduals.Training.2),
        pch = 16, col = c("green", "blue"), ylab = "Separated parts of the training sample")

Logistic.Model.Data <- data.frame(Logistic.Output = LinearModel.Training[, 3], Logistic.Input = EstimatedResiduals.Training)
LinearModel.Training.Logistic <- glm(Logistic.Output ~ Logistic.Input, data = Logistic.Model.Data, family = binomial(link = logit))
Predicted.Probabilities.Training <- predict(LinearModel.Training.Logistic, type = "response")
plot(LinearModel.Training[, 1], Predicted.Probabilities.Training)
# Create the unscrambling sequence for the training sample
Unscrambling.Sequence.Training.Logistic <- (predict(LinearModel.Training.Logistic, type = "response") > .5) * 1

# Create classified residuals
ClassifiedResiduals.Training.1 <- EstimatedResiduals.Training
ClassifiedResiduals.Training.2 <- EstimatedResiduals.Training
ClassifiedResiduals.Training.1[(Unscrambling.Sequence.Training.Logistic == 0) * (1:nSample.Training)] <- NA
ClassifiedResiduals.Training.2[(Unscrambling.Sequence.Training.Logistic == 1) * (1:nSample.Training)] <- NA
head(cbind(AllTraining = EstimatedResiduals.Training,
           Training1 = ClassifiedResiduals.Training.1,
           Training2 = ClassifiedResiduals.Training.2))
matplot(LinearModel.Training[, 1], cbind(ClassifiedResiduals.Training.1,
                                         ClassifiedResiduals.Training.2),
        pch = 16, col = c("green", "blue"), ylab = "Classified residuals, X-axis at 0")
axis(1, pos = 0.3)
LinearModel <- read.csv(file = paste(dataPath, 'Week6_Test_Sample_Test.csv', sep = "/"), header = TRUE, sep = " ")
LinearModel <- LinearModel[c(2,1)]
nSample <- length(LinearModel[, 1])
head(LinearModel)
EstimatedLinearModel<-lm(LinearModel[,2]~LinearModel[,1])
EstimatedLinearModel$coefficients
EstimatedResiduals<-EstimatedLinearModel$residuals
plot(LinearModel[,1],EstimatedResiduals)
Unscrambling.Sequence.Logistic <- (predict(LinearModel.Training.Logistic,
                                           newdata = data.frame(Logistic.Output = EstimatedResiduals, Logistic.Input = EstimatedResiduals),
                                           type = "response") > .5) * 1
res <- list(Unscrambling.Sequence.Logistic =  Unscrambling.Sequence.Logistic)
write.table(res, file = paste(dataPath,'result.csv',sep = '/'), row.names = F)

